<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <title>{{ $companyName }} - {{ __('Employee Document') }}</title>
    <style>
        @page {
            margin: 36px 56px 70px 56px;
        }

        body {
            color: #111827;
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            line-height: 1.55;
            margin: 0;
        }

        .header-table {
            border-bottom: 2px solid #111827;
            margin: 0 0 20px;
            padding-bottom: 10px;
            width: 100%;
        }

        .header-table,
        .header-table td {
            border: 0;
        }

        .logo-cell {
            padding: 0 12px 0 0;
            vertical-align: middle;
            width: 50px;
        }

        .text-cell {
            padding: 0;
            vertical-align: middle;
        }

        .company-name {
            color: #111827;
            font-size: 16px;
            font-weight: 700;
            letter-spacing: 0;
            margin: 0 0 2px;
            text-transform: uppercase;
        }

        .company-address {
            color: #4b5563;
            font-size: 9px;
            line-height: 1.35;
            margin: 0;
        }

        .meta-table {
            margin: 0 0 20px;
            width: 100%;
        }

        .meta-table,
        .meta-table td {
            border: 0;
        }

        .meta-label {
            color: #374151;
            font-size: 11px;
            font-weight: 700;
            padding: 0 8px 5px 0;
            width: 68px;
        }

        .meta-separator {
            color: #374151;
            font-size: 11px;
            padding: 0 8px 5px 0;
            width: 8px;
        }

        .meta-value {
            color: #111827;
            font-size: 11px;
            padding: 0 0 5px;
        }

        h1, h2, h3, h4 {
            margin: 0 0 12px;
        }

        h2 {
            font-size: 17px;
            letter-spacing: .02em;
            line-height: 1.35;
            margin: 4px 0 20px;
            text-transform: uppercase;
        }

        p {
            margin: 0 0 10px;
        }

        table {
            border-collapse: collapse;
            margin: 12px 0;
            width: 100%;
        }

        th, td {
            border: 1px solid #d1d5db;
            padding: 8px;
            text-align: left;
            vertical-align: top;
        }

        .footer {
            position: fixed;
            right: 0;
            bottom: -46px;
            left: 0;
            border-top: 1px solid #d1d5db;
            color: #6b7280;
            font-size: 10px;
            height: 32px;
            line-height: 1.35;
            padding-top: 8px;
        }
    </style>
</head>
<body>
    @php
        $logoPng = public_path('images/icons/logo.png');
        $logoJpeg = public_path('images/icons/logo.jpeg');
        $logoPath = file_exists($logoPng) ? $logoPng : (file_exists($logoJpeg) ? $logoJpeg : null);
        $companyAddress = \App\Models\Setting::getValue('app.company_address', '');
        $documentMeta = $documentMeta ?? [];
    @endphp

    <table class="header-table">
        <tr>
            @if ($logoPath)
                <td class="logo-cell">
                    <img src="{{ $logoPath }}" style="height: 44px; width: auto;">
                </td>
            @endif
            <td class="text-cell">
                <h1 class="company-name">{{ $companyName }}</h1>
                @if ($companyAddress)
                    <p class="company-address">{{ $companyAddress }}</p>
                @endif
            </td>
        </tr>
    </table>

    @if ($documentMeta)
        <table class="meta-table">
            @foreach ($documentMeta as $label => $value)
                @if (filled($value))
                    <tr>
                        <td class="meta-label">{{ $label }}</td>
                        <td class="meta-separator">:</td>
                        <td class="meta-value">{{ $value }}</td>
                    </tr>
                @endif
            @endforeach
        </table>
    @endif

    {!! $body !!}

    <div class="footer">
        @if ($footer)
            {!! $footer !!}
        @else
            {{ __('Generated by :app. This is a computer-generated document and may not require a physical signature.', ['app' => $companyName]) }}
        @endif
    </div>
</body>
</html>
