<?php

namespace App\Exports;

use App\Models\Payroll;
use App\Models\User;
use Illuminate\Database\Eloquent\Builder;
use Maatwebsite\Excel\Concerns\FromQuery;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;

class PayrollSummaryExport implements FromQuery, ShouldAutoSize, WithHeadings, WithMapping
{
    private int $rowNumber = 0;

    /**
     * @param  array<string, mixed>  $filters
     */
    public function __construct(
        private readonly User $actor,
        private readonly array $filters = [],
    ) {}

    public function query(): Builder
    {
        return Payroll::query()
            ->with(['user:id,name,nip,division_id,job_title_id', 'user.division:id,name', 'user.jobTitle:id,name', 'generator:id,name'])
            ->whereHas('user', fn (Builder $userQuery) => $userQuery->managedBy($this->actor))
            ->when($this->filters['month'] ?? null, fn (Builder $query, string|int $month) => $query->where('month', (int) $month))
            ->when($this->filters['year'] ?? null, fn (Builder $query, string|int $year) => $query->where('year', (int) $year))
            ->when(($this->filters['status'] ?? 'all') !== 'all', fn (Builder $query) => $query->where('status', $this->filters['status']))
            ->when($this->filters['division'] ?? null, fn (Builder $query, string|int $division) => $query->whereHas('user', fn (Builder $userQuery) => $userQuery->where('division_id', $division)))
            ->when($this->filters['job_title'] ?? null, fn (Builder $query, string|int $jobTitle) => $query->whereHas('user', fn (Builder $userQuery) => $userQuery->where('job_title_id', $jobTitle)))
            ->when($this->filters['search'] ?? null, function (Builder $query, string $search): void {
                $query->whereHas('user', function (Builder $userQuery) use ($search): void {
                    $userQuery
                        ->where('name', 'like', '%'.$search.'%')
                        ->orWhere('nip', 'like', '%'.$search.'%');
                });
            })
            ->orderBy('year')
            ->orderBy('month')
            ->orderBy('user_id')
            ->orderBy('id');
    }

    public function headings(): array
    {
        return [
            '#',
            'Year',
            'Month',
            'Employee',
            'NIP',
            'Division',
            'Job Title',
            'Type',
            'Basic Salary',
            'Overtime Pay',
            'Total Allowance',
            'Total Deduction',
            'Net Salary',
            'Status',
            'Generated By',
            'Paid At',
            'Created At',
            'Updated At',
        ];
    }

    /**
     * @return array<int, mixed>
     */
    public function map($payroll): array
    {
        return [
            ++$this->rowNumber,
            $payroll->year,
            $payroll->month,
            $payroll->user?->name,
            (string) ($payroll->user?->nip ?? ''),
            $payroll->user?->division?->name,
            $payroll->user?->jobTitle?->name,
            $payroll->type,
            $payroll->basic_salary,
            $payroll->overtime_pay,
            $payroll->total_allowance,
            $payroll->total_deduction,
            $payroll->net_salary,
            __($payroll->status),
            $payroll->generator?->name,
            $payroll->paid_at?->format('Y-m-d H:i:s'),
            $payroll->created_at?->format('Y-m-d H:i:s'),
            $payroll->updated_at?->format('Y-m-d H:i:s'),
        ];
    }
}
