<?php

use App\Models\EmployeeDocumentRequest;
use App\Models\EmployeeDocumentType;
use App\Models\User;
use Illuminate\Contracts\Console\Kernel;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

require __DIR__.'/../vendor/autoload.php';

$app = require __DIR__.'/../bootstrap/app.php';
$app->make(Kernel::class)->bootstrap();

$email = getenv('E2E_EMAIL') ?: 'apk.e2e.user@paspapan.test';
$password = getenv('E2E_PASSWORD') ?: '12345678';
$marker = getenv('E2E_MARKER') ?: 'APK E2E document upload';

$userPayload = [
    'nip' => 'APK-E2E-001',
    'name' => 'APK E2E User',
    'phone' => '081234567899',
    'gender' => 'male',
    'address' => 'APK E2E Address',
    'password' => Hash::make($password),
    'group' => 'user',
    'email_verified_at' => now(),
];

foreach ([
    'city' => 'Jakarta',
    'employment_status' => 'active',
] as $column => $value) {
    if (Schema::hasColumn('users', $column)) {
        $userPayload[$column] = $value;
    }
}

$user = User::query()->updateOrCreate(['email' => $email], $userPayload);
$user->forceFill(['email_verified_at' => now()])->save();

if (Schema::hasTable('sessions') && Schema::hasColumn('sessions', 'user_id')) {
    DB::table('sessions')->where('user_id', $user->id)->delete();
}

$type = EmployeeDocumentType::query()->updateOrCreate(
    ['code' => 'npwp'],
    [
        'name' => 'NPWP',
        'category' => 'finance',
        'is_active' => true,
        'employee_requestable' => false,
        'admin_requestable' => true,
        'requires_employee_upload' => true,
        'auto_generate_enabled' => false,
    ],
);

$request = EmployeeDocumentRequest::query()
    ->where('user_id', $user->id)
    ->where('purpose', $marker)
    ->whereIn('status', [
        EmployeeDocumentRequest::STATUS_REQUESTED,
        EmployeeDocumentRequest::STATUS_UPLOAD_PROCESSING,
    ])
    ->latest()
    ->first();

if (! $request) {
    $request = EmployeeDocumentRequest::query()->create([
        'user_id' => $user->id,
        'document_type_id' => $type->id,
        'document_type' => $type->code,
        'request_source' => EmployeeDocumentRequest::SOURCE_ADMIN,
        'purpose' => $marker,
        'details' => 'Upload fixture generated by APK document upload E2E.',
        'due_date' => now()->addWeek()->toDateString(),
        'status' => EmployeeDocumentRequest::STATUS_REQUESTED,
        'metadata' => ['e2e_run' => (string) Str::uuid()],
    ]);
} else {
    $previousUpload = data_get($request->metadata, 'employee_upload.staged_path');

    if (is_string($previousUpload) && Storage::disk('local')->exists($previousUpload)) {
        Storage::disk('local')->delete($previousUpload);
    }

    $request->update([
        'status' => EmployeeDocumentRequest::STATUS_REQUESTED,
        'uploaded_path' => null,
        'uploaded_original_name' => null,
        'uploaded_at' => null,
        'metadata' => ['e2e_run' => (string) Str::uuid()],
    ]);
}

echo json_encode([
    'email' => $email,
    'password' => $password,
    'request_id' => $request->id,
    'marker' => $marker,
], JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES).PHP_EOL;
