<?php

declare(strict_types=1);

$legacyInlineSvgFiles = [
    'resources/views/attendances/history.blade.php',
    'resources/views/attendances/scan.blade.php',
    'resources/views/auth/forgot-password.blade.php',
    'resources/views/auth/login.blade.php',
    'resources/views/auth/reset-password.blade.php',
    'resources/views/layouts/app.blade.php',
    'resources/views/livewire/admin/analytics-dashboard.blade.php',
    'resources/views/livewire/admin/announcement-manager.blade.php',
    'resources/views/livewire/admin/attendance.blade.php',
    'resources/views/livewire/admin/holiday-manager.blade.php',
    'resources/views/livewire/admin/import-export/user.blade.php',
    'resources/views/livewire/admin/leave-approval.blade.php',
    'resources/views/livewire/admin/master-data/admin.blade.php',
    'resources/views/livewire/admin/master-data/division.blade.php',
    'resources/views/livewire/admin/master-data/education.blade.php',
    'resources/views/livewire/admin/master-data/job-title.blade.php',
    'resources/views/livewire/admin/master-data/shift.blade.php',
    'resources/views/livewire/admin/notifications-page.blade.php',
    'resources/views/livewire/admin/overtime-manager.blade.php',
    'resources/views/livewire/admin/payroll-manager.blade.php',
    'resources/views/livewire/admin/payroll-settings.blade.php',
    'resources/views/livewire/admin/reimbursement-manager.blade.php',
    'resources/views/livewire/admin/system-maintenance.blade.php',
    'resources/views/livewire/user/attendance-correction-page.blade.php',
    'resources/views/livewire/user/overtime-request.blade.php',
    'resources/views/livewire/user/team-approvals-history.blade.php',
    'resources/views/livewire/user/upcoming-events-widget.blade.php',
    'resources/views/profile/logout-other-browser-sessions-form.blade.php',
    'resources/views/profile/update-profile-information-form.blade.php',
];

$legacyTableFiles = [
    'resources/views/livewire/admin/activity-logs.blade.php',
    'resources/views/livewire/admin/announcement-manager.blade.php',
    'resources/views/livewire/admin/appraisal-manager.blade.php',
    'resources/views/livewire/admin/asset-manager.blade.php',
    'resources/views/livewire/admin/attendance-correction-manager.blade.php',
    'resources/views/livewire/admin/attendance.blade.php',
    'resources/views/livewire/admin/dashboard.blade.php',
    'resources/views/livewire/admin/employee-document-request-manager.blade.php',
    'resources/views/livewire/admin/employees.blade.php',
    'resources/views/livewire/admin/holiday-manager.blade.php',
    'resources/views/livewire/admin/import-export/attendance.blade.php',
    'resources/views/livewire/admin/import-export/user.blade.php',
    'resources/views/livewire/admin/leave-approval.blade.php',
    'resources/views/livewire/admin/master-data/admin.blade.php',
    'resources/views/livewire/admin/master-data/division.blade.php',
    'resources/views/livewire/admin/master-data/education.blade.php',
    'resources/views/livewire/admin/master-data/job-title.blade.php',
    'resources/views/livewire/admin/master-data/shift.blade.php',
    'resources/views/livewire/admin/payroll-manager.blade.php',
    'resources/views/livewire/admin/payroll-settings.blade.php',
    'resources/views/livewire/admin/reimbursement-manager.blade.php',
    'resources/views/livewire/admin/settings/kpi-settings.blade.php',
    'resources/views/livewire/shared/finance/cash-advance-manager-content.blade.php',
    'resources/views/livewire/user/attendance-correction-page.blade.php',
    'resources/views/livewire/user/employee-document-request-page.blade.php',
    'resources/views/livewire/user/partials/team-attendance-corrections-history.blade.php',
    'resources/views/livewire/user/partials/team-attendance-corrections-pending.blade.php',
    'resources/views/livewire/user/partials/team-shift-swaps-history.blade.php',
    'resources/views/livewire/user/partials/team-shift-swaps-pending.blade.php',
    'resources/views/livewire/user/shift-swap-request-page.blade.php',
    'resources/views/livewire/user/team-approvals-history.blade.php',
    'resources/views/livewire/user/team-approvals.blade.php',
];

return array_merge(
    array_map(
        static fn (string $file): array => [
            'file' => $file,
            'rule' => 'raw_inline_svg',
            'reason' => 'Legacy inline SVG pending Heroicons migration.',
        ],
        $legacyInlineSvgFiles,
    ),
    array_map(
        static fn (string $file): array => [
            'file' => $file,
            'rule' => 'table_usage',
            'reason' => 'Legacy table layout pending card-first mobile migration.',
        ],
        $legacyTableFiles,
    ),
);
